name: Generate and Publish Proto

on:
  push:
    branches: [master]

env:
  PROTOC_VERSION: 28.3
  BUF_VERSION: 1.47.2

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout proto repo
      uses: actions/checkout@v4
      with:
        path: definitions

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.0'

    - name: Install protoc
      run: |
        PROTOC_ZIP=protoc-${PROTOC_VERSION}-linux-x86_64.zip
        curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VERSION}/${PROTOC_ZIP}
        sudo unzip -o ${PROTOC_ZIP} -d /usr/local bin/protoc
        sudo unzip -o ${PROTOC_ZIP} -d /usr/local 'include/*'
        rm -f ${PROTOC_ZIP}
        protoc --version

    - name: Install protoc-gen plugins
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
        go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@latest
        go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@latest
        go install github.com/envoyproxy/protoc-gen-validate@latest

    - name: Install buf
      run: |
        curl -sSL "https://github.com/bufbuild/buf/releases/download/v${BUF_VERSION}/buf-$(uname -s)-$(uname -m)" \
          -o "/usr/local/bin/buf"
        chmod +x "/usr/local/bin/buf"
        buf --version

    - name: Generate Go code with buf
      run: |
        cd definitions
        buf dep update
        buf build
        buf generate

    - name: Checkout generated code repo
      uses: actions/checkout@v4
      with:
        repository: YumikoKawaii/rpc.com
        token: ${{ secrets.PAT_TOKEN }}
        path: target

    - name: Copy generated files
      run: |
        mkdir -p target/protobuf
        if [ -d "definitions/rpc.com" ] && [ "$(ls -A definitions/rpc.com)" ]; then
          cp -r definitions/rpc.com/* target/protobuf/
        else
          echo "No generated files found in definitions/rpc.com"
          exit 1
        fi

#    - name: Update Go dependencies
#      run: |
#        cd target
#        go mod tidy

    - name: Commit and push
      run: |
        cd target
        git config user.name "YumikoKawaii"
        git config user.email "yumiko.stl@gmail.com"
        git add .
        git diff --quiet && git diff --staged --quiet || git commit -m "rpc version: ${{ github.sha }}"
        git push